version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/php/8.1
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    environment:
      - APP_ENV=local
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
